### ISSUE TITLE
test pcm::playback_to_default sometimes fails

### ISSUE THREAD

**Issue by Boddlnagg** [diwic/alsa-rs#24]
This is the result of running `cargo test` (on my PR branch, but I didn't change anything outside the `seq` module), although sometimes this test passes:

```
failures:

---- pcm::playback_to_default stdout ----
	PCM status: Prepared, HwParams(channels: Ok(1), rate: Ok(44100) Hz, format: Ok(S16LE), access: Ok(RWInterleaved), period size: Ok(2048) frames, buffer size: Ok(2097152) frames)
== PCM dump ==
ALSA <-> PulseAudio PCM I/O Plugin
Its setup is:
  stream       : PLAYBACK
  access       : RW_INTERLEAVED
  format       : S16_LE
  subformat    : STD
  channels     : 1
  rate         : 44100
  exact rate   : 44100 (44100/1)
  msbits       : 16
  buffer_size  : 2097152
  period_size  : 2048
  period_time  : 46439
  tstamp_mode  : NONE
  tstamp_type  : GETTIMEOFDAY
  period_step  : 1
  avail_min    : 2048
  period_event : 0
  start_threshold  : 1
  stop_threshold   : 2097152
  silence_threshold: 0
  silence_size : 0
  boundary     : 4611686018427387904

thread 'pcm::playback_to_default' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Some("snd_pcm_writei"), -32)', /checkout/src/libcore/result.rs:859
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:737
   1: alsa::pcm::playback_to_default
             at ./src/pcm.rs:750
   2: <F as test::FnBox<T>>::call_box
             at /checkout/src/libtest/lib.rs:1368
             at /checkout/src/libcore/ops.rs:2606
             at /checkout/src/libtest/lib.rs:140
   3: std::panicking::try::do_call
             at /checkout/src/libtest/lib.rs:1314
             at /checkout/src/libstd/panic.rs:296
             at /checkout/src/libstd/panicking.rs:454
   4: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
   5: std::panicking::try::do_call
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libtest/lib.rs:1313
             at /checkout/src/libstd/panic.rs:296
             at /checkout/src/libstd/panicking.rs:454
   6: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
   7: <F as alloc::boxed::FnBox<A>>::call_box
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/thread/mod.rs:360
             at /checkout/src/liballoc/boxed.rs:640
   8: std::sys::imp::thread::Thread::new::thread_start
             at /checkout/src/liballoc/boxed.rs:650
             at /checkout/src/libstd/sys_common/thread.rs:21
             at /checkout/src/libstd/sys/unix/thread.rs:84
   9: start_thread
  10: clone


failures:
    pcm::playback_to_default

test result: FAILED. 20 passed; 1 failed; 0 ignored; 0 measured
```

**Comment by diwic** [comment]
I see the same failure. I think it has to do with starting two playbacks simultaneously. I believe it's something inside ALSA or PulseAudio rather than my bindings. Then I switched computers and now it happens very rarely, so I forgot about it...

**Comment by hansihe** [comment]
I am having the same problem.

It happens in the test suite, but it also happens on its own when there is no other sounds playing on the machine.

**Comment by diwic** [comment]
I think I solved it. The stream had a very low start threshold for some reason, so it ended up as an XRUN. I fixed the example(s) to have a higher start threshold. I think it's fixed now, but do reopen if you see it again.
